workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build AAB
        script: |
          flutter build appbundle --release --android-skip-build-dependency-validation
          echo "✅ AAB build complete."
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Flutter build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
